language: cpp

env:
  global:
    # Variables for Coverity scan
    - STANDARD_BUILD_COMMAND="make all -B"
    - COVERITY_SCAN_PROJECT_NAME="corporateshark%2FWalCommander"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="walcommander@linderdaum.com"
    # Regular expression selects on which branches to run analysis
    # Be aware of quotas. Do not run on every branch/commit
    - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"

    # Optionally execute a command immediately before cov-build, i.e.
    # pre-configuration required for the COVERITY_SCAN_BUILD_COMMAND
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND=""

    # Insert the cov-build build commmand here
    - COVERITY_SCAN_BUILD_COMMAND=$STANDARD_BUILD_COMMAND

    # COVERITY_SCAN_TOKEN via "travis encrypt" using the repo's public key
    - COVERITY_SCAN_TOKEN: "_x7cJjh1irddf1NDaMjTEQ"

    # ---- END Project-specific configuration

    - COVERITY_SCAN_BUILD_URL="https://gist.githubusercontent.com/KonstantinKuklin/63df870cb63519d49bce/raw"
    - COVERITY_SCAN_BUILD="curl -s $COVERITY_SCAN_BUILD_URL | bash"
    
    
before_script:
    - gcc -v
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install gcc-4.8 g++-4.8 libsmbclient-dev libssh2-1-dev
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++
    - gcc -v 

compiler:
    - gcc

script:
    - eval "$COVERITY_SCAN_BUILD"
